# Generated by Django 2.0 on 2017-12-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Asesor')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fuente', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(null=True)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Par'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.TipoContacto'),
        ),
    ]
