# Generated by Django 2.0 on 2017-12-19 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Asesor'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Autor'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Par'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Modulo'),
        ),
    ]
