# Generated by Django 2.0 on 2017-12-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20171219_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesor',
            options={'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='par',
            options={'verbose_name': 'Par', 'verbose_name_plural': 'Pares'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='tipocontacto',
            options={'verbose_name': 'Tipo de contacto', 'verbose_name_plural': 'Tipos de contacto'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
