# Generated by Django 2.0 on 2017-12-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_auto_20171219_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Modulo'),
            preserve_default=False,
        ),
    ]
