# Generated by Django 2.0 on 2017-12-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_contacto_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='seguimiento.Modulo'),
        ),
    ]
