# Generated by Django 2.0 on 2017-12-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_auto_20171220_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='seguimiento.TipoContacto'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='seguimiento.Asesor'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='seguimiento.Autor'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='seguimiento.Par'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='seguimiento.Modulo'),
        ),
    ]
